chore(dev-deps): ⬆️ update devdependencies (#195)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react) ([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped)) | [`18.2.17` -> `18.2.18`](https://renovatebot.com/diffs/npm/@types%2freact/18.2.17/18.2.18) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2freact/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2freact/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2freact/18.2.17/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2freact/18.2.17/18.2.18?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [dedent](https://togithub.com/dmnd/dedent) | [`1.3.0` -> `1.5.1`](https://renovatebot.com/diffs/npm/dedent/1.3.0/1.5.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/dedent/1.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/dedent/1.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/dedent/1.3.0/1.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/dedent/1.3.0/1.5.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [eslint](https://eslint.org) ([source](https://togithub.com/eslint/eslint)) | [`8.45.0` -> `8.46.0`](https://renovatebot.com/diffs/npm/eslint/8.45.0/8.46.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/eslint/8.46.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint/8.46.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint/8.45.0/8.46.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint/8.45.0/8.46.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [eslint-config-prettier](https://togithub.com/prettier/eslint-config-prettier) | [`8.9.0` -> `8.10.0`](https://renovatebot.com/diffs/npm/eslint-config-prettier/8.9.0/8.10.0) | [![age](https://developer.mend.io/api/mc/badges/age/npm/eslint-config-prettier/8.10.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/eslint-config-prettier/8.10.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/eslint-config-prettier/8.9.0/8.10.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/eslint-config-prettier/8.9.0/8.10.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [knip](https://togithub.com/webpro/knip) | [`2.17.1` -> `2.17.3`](https://renovatebot.com/diffs/npm/knip/2.17.1/2.17.3) | [![age](https://developer.mend.io/api/mc/badges/age/npm/knip/2.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/knip/2.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/knip/2.17.1/2.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/knip/2.17.1/2.17.3?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [prettier](https://prettier.io) ([source](https://togithub.com/prettier/prettier)) | [`3.0.0` -> `3.0.1`](https://renovatebot.com/diffs/npm/prettier/3.0.0/3.0.1) | [![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.0.0/3.0.1?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>dmnd/dedent (dedent)</summary>

### [`v1.5.1`](https://togithub.com/dmnd/dedent/blob/HEAD/CHANGELOG.md#151)

[Compare Source](https://togithub.com/dmnd/dedent/compare/v1.5.0...v1.5.1)

-   fix: add missing dedent.d.mts entry to package.json files ([#&#8203;73](https://togithub.com/dmnd/dedent/issues/73))

### [`v1.5.0`](https://togithub.com/dmnd/dedent/blob/HEAD/CHANGELOG.md#150)

[Compare Source](https://togithub.com/dmnd/dedent/compare/v1.4.0...v1.5.0)

-   feat: add options with escapeSpecialCharacters ([#&#8203;65](https://togithub.com/dmnd/dedent/issues/65))

### [`v1.4.0`](https://togithub.com/dmnd/dedent/blob/HEAD/CHANGELOG.md#140)

[Compare Source](https://togithub.com/dmnd/dedent/compare/v1.3.0...v1.4.0)

-   fix: add missing exports field to package.json ([#&#8203;59](https://togithub.com/dmnd/dedent/issues/59))
-   fix: fix missing ESM type definition file ([#&#8203;67](https://togithub.com/dmnd/dedent/issues/67))

</details>

<details>
<summary>eslint/eslint (eslint)</summary>

### [`v8.46.0`](https://togithub.com/eslint/eslint/releases/tag/v8.46.0)

[Compare Source](https://togithub.com/eslint/eslint/compare/v8.45.0...v8.46.0)

#### Features

-   [`8a93438`](https://togithub.com/eslint/eslint/commit/8a9343871f7dade19d910ca8e2a4177bfca28b64) feat: `require-unicode-regexp` support `v` flag ([#&#8203;17402](https://togithub.com/eslint/eslint/issues/17402)) (SUZUKI Sosuke)
-   [`1a2f966`](https://togithub.com/eslint/eslint/commit/1a2f966fabe35103141d2f936180d2f1a72154db) feat: `no-useless-escape` support `v` flag ([#&#8203;17420](https://togithub.com/eslint/eslint/issues/17420)) (Yosuke Ota)
-   [`ee68d1d`](https://togithub.com/eslint/eslint/commit/ee68d1d9630892d99ae0d8dabe2f9f8d3b1338be) feat: `no-empty-character-class` support `v` flag ([#&#8203;17419](https://togithub.com/eslint/eslint/issues/17419)) (Milos Djermanovic)
-   [`853d32b`](https://togithub.com/eslint/eslint/commit/853d32baa8934c08b59a738470b72522e1505f6f) feat: deprecate no-return-await ([#&#8203;17417](https://togithub.com/eslint/eslint/issues/17417)) (Carlos Lopez)
-   [`d4f02e4`](https://togithub.com/eslint/eslint/commit/d4f02e4bf1b9ae4e1fc8f2bc4e4851ae3c36a127) feat: `no-control-regex` support `v` flag ([#&#8203;17405](https://togithub.com/eslint/eslint/issues/17405)) (Yosuke Ota)
-   [`2a35f3e`](https://togithub.com/eslint/eslint/commit/2a35f3e6ed27deafbebba48b6aec570d3abf9974) feat: `prefer-named-capture-group` support `v` flag ([#&#8203;17409](https://togithub.com/eslint/eslint/issues/17409)) (Yosuke Ota)
-   [`8ca8b50`](https://togithub.com/eslint/eslint/commit/8ca8b50b0425b3bad34a9505bc3095168e2f59d8) feat: Better error message for flat config plugins ([#&#8203;17399](https://togithub.com/eslint/eslint/issues/17399)) (Nicholas C. Zakas)
-   [`509f753`](https://togithub.com/eslint/eslint/commit/509f75395035822280245772e2a95732a0dde0e1) feat: `no-misleading-character-class` support `v` flag ([#&#8203;17406](https://togithub.com/eslint/eslint/issues/17406)) (Yosuke Ota)
-   [`3caf514`](https://togithub.com/eslint/eslint/commit/3caf51487decdf93a4b17765a2af2a51c337e974) feat: `no-regex-spaces` support `v` flag ([#&#8203;17407](https://togithub.com/eslint/eslint/issues/17407)) (Yosuke Ota)
-   [`b7fad2b`](https://togithub.com/eslint/eslint/commit/b7fad2b52f23667628cf209663795a721c88d0ba) feat: `prefer-regex-literals` support `v` flag ([#&#8203;17410](https://togithub.com/eslint/eslint/issues/17410)) (Yosuke Ota)
-   [`a6a3ad4`](https://togithub.com/eslint/eslint/commit/a6a3ad4ae438ea7fc3a1d97cd2555f6534b565f1) feat: `no-useless-backreference` support `v` flag ([#&#8203;17408](https://togithub.com/eslint/eslint/issues/17408)) (Yosuke Ota)
-   [`94954a7`](https://togithub.com/eslint/eslint/commit/94954a715448d5794f2892bf212fe986b43228ed) feat: `no-invalid-regexp` support `v` flag ([#&#8203;17404](https://togithub.com/eslint/eslint/issues/17404)) (Yosuke Ota)
-   [`1af6eac`](https://togithub.com/eslint/eslint/commit/1af6eac5727080c809e37c07dc729b44ef24483c) feat: adds option for allowing empty object patterns as parameter ([#&#8203;17365](https://togithub.com/eslint/eslint/issues/17365)) (Tanuj Kanti)
-   [`cf03104`](https://togithub.com/eslint/eslint/commit/cf03104b278fea59ef46e09f667110f5eaaf95e3) feat: Improve config error messages ([#&#8203;17385](https://togithub.com/eslint/eslint/issues/17385)) (Nicholas C. Zakas)

#### Bug Fixes

-   [`9803c7c`](https://togithub.com/eslint/eslint/commit/9803c7c04078f0672d8a480fd39cf3bbef8017e6) fix: FlatESLint#getRulesMetaForResults shouldn't throw on unknown rules ([#&#8203;17393](https://togithub.com/eslint/eslint/issues/17393)) (Milos Djermanovic)
-   [`42faa17`](https://togithub.com/eslint/eslint/commit/42faa17b1c93f801b14bea2840d1d528e25c7211) fix: Update no-loop-func to not overlap with no-undef ([#&#8203;17358](https://togithub.com/eslint/eslint/issues/17358)) (Matt Wilkinson)

#### Documentation

-   [`4d474e3`](https://togithub.com/eslint/eslint/commit/4d474e351ba6ce0242f18e55c27cb3ae17b84f63) docs: update with TypeScript info ([#&#8203;17423](https://togithub.com/eslint/eslint/issues/17423)) (James)
-   [`091f44e`](https://togithub.com/eslint/eslint/commit/091f44e4c72007edb2ac6d4db4eafa5501e41e94) docs: File extension named processor deprecation ([#&#8203;17362](https://togithub.com/eslint/eslint/issues/17362)) (Matt Wilkinson)
-   [`9254a6c`](https://togithub.com/eslint/eslint/commit/9254a6cea845dfaf2f3f52f718cb9b071853aa09) docs: Update README (GitHub Actions Bot)
-   [`6d6dc51`](https://togithub.com/eslint/eslint/commit/6d6dc5141f535728029eef8735854a421bc08eba) docs: fix overlapping of `open in playground` button ([#&#8203;17403](https://togithub.com/eslint/eslint/issues/17403)) (Tanuj Kanti)
-   [`7fc3a2c`](https://togithub.com/eslint/eslint/commit/7fc3a2ce68979a2c2a6fc779e647b3004ab6f4ac) docs: Add private class features info to no-underscore-dangle ([#&#8203;17386](https://togithub.com/eslint/eslint/issues/17386)) (Matt Wilkinson)
-   [`da73e58`](https://togithub.com/eslint/eslint/commit/da73e583e1703a420551d8fa8f7c70b56dc88dd5) docs: Migrating `eslint-env` configuration comments ([#&#8203;17390](https://togithub.com/eslint/eslint/issues/17390)) (Francesco Trotta)
-   [`80dffed`](https://togithub.com/eslint/eslint/commit/80dffed4c81dcc71fb72bc187aff2f87d141a6ed) docs: fix Ignoring Files section in config migration guide ([#&#8203;17392](https://togithub.com/eslint/eslint/issues/17392)) (Milos Djermanovic)
-   [`8a9abb7`](https://togithub.com/eslint/eslint/commit/8a9abb7cf424bd49d45c09345dc45ae95f29cc9d) docs: Update README (GitHub Actions Bot)
-   [`7e9be4b`](https://togithub.com/eslint/eslint/commit/7e9be4bd7331d0e8e8e0af0b075a2f6d28d1bea3) docs: Update README (GitHub Actions Bot)
-   [`0b0bbe0`](https://togithub.com/eslint/eslint/commit/0b0bbe07d4fb0870f3916e975b8ec6978f838077) docs: Update README (GitHub Actions Bot)

#### Chores

-   [`d1eb7e4`](https://togithub.com/eslint/eslint/commit/d1eb7e46e954c64af8d7d13d087b3a18f43e6d72) chore: Update ecosystem dependencies ([#&#8203;17427](https://togithub.com/eslint/eslint/issues/17427)) (Nicholas C. Zakas)
-   [`fab9e97`](https://togithub.com/eslint/eslint/commit/fab9e97ef9dff40e98a5b3b97bdd3b0ff5439d46) chore: package.json update for eslint-config-eslint release (ESLint Jenkins)
-   [`6246711`](https://togithub.com/eslint/eslint/commit/6246711e0650d03afe044c36acde048ed2d39ee3) chore: package.json update for [@&#8203;eslint/js](https://togithub.com/eslint/js) release (ESLint Jenkins)
-   [`0aa0bc3`](https://togithub.com/eslint/eslint/commit/0aa0bc365a5425440c8e86c96104d0053a51b602) chore: Add PRs to triage project ([#&#8203;17421](https://togithub.com/eslint/eslint/issues/17421)) (Nicholas C. Zakas)

</details>

<details>
<summary>prettier/eslint-config-prettier (eslint-config-prettier)</summary>

### [`v8.10.0`](https://togithub.com/prettier/eslint-config-prettier/blob/HEAD/CHANGELOG.md#Version-8100-2023-08-03)

[Compare Source](https://togithub.com/prettier/eslint-config-prettier/compare/v8.9.0...v8.10.0)

-   Added: \[max-statements-per-line]. Thanks to [@&#8203;Zamiell](https://togithub.com/Zamiell)!

</details>

<details>
<summary>webpro/knip (knip)</summary>

### [`v2.17.3`](https://togithub.com/webpro/knip/releases/tag/2.17.3)

[Compare Source](https://togithub.com/webpro/knip/compare/2.17.2...2.17.3)

-   Update dependencies ([`a9bbe5f`](https://togithub.com/webpro/knip/commit/a9bbe5f))
-   Add `.yml` and `.yaml` to extensions to ignore (fixes [#&#8203;178](https://togithub.com/webpro/knip/issues/178)) ([`6d5835b`](https://togithub.com/webpro/knip/commit/6d5835b))
-   feat: silent in CI ([#&#8203;180](https://togithub.com/webpro/knip/issues/180)) ([`9955f35`](https://togithub.com/webpro/knip/commit/9955f35))
-   docs: document ci + show-progress ([#&#8203;179](https://togithub.com/webpro/knip/issues/179)) ([`f0a22b3`](https://togithub.com/webpro/knip/commit/f0a22b3))

### [`v2.17.2`](https://togithub.com/webpro/knip/releases/tag/2.17.2)

[Compare Source](https://togithub.com/webpro/knip/compare/2.17.1...2.17.2)

-   Vitest reporter can be reporter instance (fixes [#&#8203;175](https://togithub.com/webpro/knip/issues/175)) ([`badd7af`](https://togithub.com/webpro/knip/commit/badd7af))
-   Fix up ignored/enabled workspace getters (closes [#&#8203;174](https://togithub.com/webpro/knip/issues/174)) ([`04acb61`](https://togithub.com/webpro/knip/commit/04acb61))
-   Improve npx dependency resolver ([`482396e`](https://togithub.com/webpro/knip/commit/482396e))

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

### [`v3.0.1`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#301)

[Compare Source](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

[diff](https://togithub.com/prettier/prettier/compare/3.0.0...3.0.1)

##### Fix cursor positioning for a special case ([#&#8203;14812](https://togithub.com/prettier/prettier/pull/14812) by [@&#8203;fisker](https://togithub.com/fisker))



```js
// <|> is the cursor position

/* Input */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>  } from "fs"

/* Prettier 3.0.0 */
// All messages are represented in JSON.
// So, the prettier.py <|>controls a subprocess which spawns "node {this_file}".
import {} from "fs"

/* Prettier 3.0.1 */
// All messages are represented in JSON.
// So, the prettier.py controls a subprocess which spawns "node {this_file}".
import {<|>} from "fs"
```

##### Fix plugins/estree.d.ts to make it a module ([#&#8203;15018](https://togithub.com/prettier/prettier/pull/15018) by [@&#8203;kingyue737](https://togithub.com/kingyue737))

Add `export {}` in `plugins/estree.d.ts` to fix the "File is not a module" error

##### Add parenthesis around leading multiline comment in return statement ([#&#8203;15037](https://togithub.com/prettier/prettier/pull/15037) by [@&#8203;auvred](https://togithub.com/auvred))



```jsx
// Input
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  )
}

// Prettier 3.0.0
function fn() {
  return /**
   * @&#8203;type {...}
   */ expresssion;
}

// Prettier 3.0.1
function fn() {
  return (
    /**
     * @&#8203;type {...}
     */ expresssion
  );
}
```

##### Add support for Vue "Generic Components" ([#&#8203;15066](https://togithub.com/prettier/prettier/pull/15066) by [@&#8203;auvred](https://togithub.com/auvred))

https://blog.vuejs.org/posts/vue-3-3#generic-components



```vue
<!-- Input -->
<script setup lang="ts" generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"></script>

<!-- Prettier 3.0.0 -->
<script
  setup
  lang="ts"
  generic="T extends Type1 & Type2 & (Type3 | Type4), U extends string | number | boolean"
></script>

<!-- Prettier 3.0.1 -->
<script
  setup
  lang="ts"
  generic="
    T extends Type1 & Type2 & (Type3 | Type4),
    U extends string | number | boolean
  "
></script>
```

##### Fix comments print in `IfStatement` ([#&#8203;15076](https://togithub.com/prettier/prettier/pull/15076) by [@&#8203;fisker](https://togithub.com/fisker))



```js
function a(b) {
  if (b) return 1; // comment
  else return 2;
}

/* Prettier 3.0.0 */
Error: Comment "comment" was not printed. Please report this error!

/* Prettier 3.0.1 */
function a(b) {
  if (b) return 1; // comment
  else return 2;
}
```

##### Add missing type definition for `printer.preprocess` ([#&#8203;15123](https://togithub.com/prettier/prettier/pull/15123) by [@&#8203;so1ve](https://togithub.com/so1ve))

```diff
export interface Printer<T = any> {
  // ...
+ preprocess?:
+   | ((ast: T, options: ParserOptions<T>) => T | Promise<T>)
+   | undefined;
}
```

##### Add missing `getVisitorKeys` method type definition for `Printer` ([#&#8203;15125](https://togithub.com/prettier/prettier/pull/15125) by [@&#8203;auvred](https://togithub.com/auvred))

```tsx
const printer: Printer = {
  print: () => [],
  getVisitorKeys(node, nonTraversableKeys) {
    return ["body"];
  },
};
```

##### Add typing to support `readonly` array properties of AST Node ([#&#8203;15127](https://togithub.com/prettier/prettier/pull/15127) by [@&#8203;auvred](https://togithub.com/auvred))



```tsx
// Input
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");

// Prettier 3.0.0
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
//                  ^ Argument of type '"readonlyArray"' is not assignable to parameter of type '"regularArray"'. ts(2345)

// Prettier 3.0.1
interface TestNode {
  readonlyArray: readonly string[];
}

declare const path: AstPath<TestNode>;

path.map(() => "", "readonlyArray");
```

##### Add space before unary minus followed by a function call ([#&#8203;15129](https://togithub.com/prettier/prettier/pull/15129) by [@&#8203;pamelalozano](https://togithub.com/pamelalozano))



```less
// Input
div {
  margin: - func();
}

// Prettier 3.0.0
div {
  margin: -func();
}

// Prettier 3.0.1
div {
  margin: - func();
}
```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on Monday" in timezone Asia/Kolkata, Automerge - At any time (no schedule defined).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get [config help](https://togithub.com/renovatebot/renovate/discussions) if that's undesired.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/timelessco/next-ts-app).